services:
  burgerorderer:
    build: ./Containers/BurgerOrderer
    ports:
      - "5000:5000"
    depends_on:
      - kitchen

  kitchen:
    build: ./Containers/KitchenView
    ports:
      - "5001:5001"
