version: '3.8'

services:
  burgerorderer:
    build: ./Containers/BurgerOrderer
    ports:
      - "5000:5000"
    depends_on:
      - kitchen
      - mongo

  kitchen:
    build: ./Containers/KitchenView
    ports:
      - "5001:5001"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
